language: python
python:
  - 3.6
  - 2.7
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/test_utils'
  matrix:
    - DJANGO='django~=2.0.0' DRF='djangorestframework~=3.11.0'
    - DJANGO='django~=1.11.0' DRF='djangorestframework~=3.9.1'
    - DJANGO='django~=1.10.0' DRF='djangorestframework~=3.6.0'
matrix:
  exclude:
    - env: DJANGO='django~=2.0.0'
      python: 2.7
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'CREATE DATABASE test_utils' -U postgres;
install:
  - pip install -r requirements.txt
  - pip install --upgrade $DJANGO
  - pip install --upgrade $DRF
