language: python
python:
  - 3.4
  - 2.7
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/test_utils'
  matrix:
    - DJANGO='django>=1.9,<1.10' DRF='djangorestframework>=3.0.5,<3.4'
    - DJANGO='django>=1.8,<1.9' DRF='djangorestframework>=3.0.5,<3.4'
install:
  - psql -c 'CREATE DATABASE test_utils' -U postgres;
  - pip install -r requirements.txt
  - pip install --upgrade $DJANGO
  - pip install --upgrade $DRF
