language: python
python:
  - 3.6
  - 2.7
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/test_utils'
  matrix:
    - DJANGO='django~=1.11.0' DRF='djangorestframework~=3.9.1'
    - DJANGO='django~=1.8.0' DRF='djangorestframework~=3.6.0'
install:
  - psql -c 'CREATE DATABASE test_utils' -U postgres;
  - pip install -r requirements.txt
  - pip install --upgrade $DJANGO
  - pip install --upgrade $DRF
