language: python
python:
  - 3.4
  - 2.7
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/test_utils'
  matrix:
    - DJANGO='django>=1.7,<1.8'
    - DJANGO='django>=1.6,<1.7'
install:
  - psql -c 'CREATE DATABASE test_utils' -U postgres;
  - pip install -r test_requirements.txt
  - pip install $DJANGO
